### ISSUE TITLE
How to show mini navigation bar 

### ISSUE THREAD

**Issue by syarizat** [mukyasa/MMGooglePlayNewsStand#1]
Hello friend,

How to show mini navigation bar if i scrolling up from bottom of list without scrolling up to the top.

Thank You

**Comment by mukyasa** [comment]
Sorry RodrigezJson i didn't got your question

**Comment by syarizat** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8197462/11177361/089e5c40-8c80-11e5-9429-3087d4e3058c.png)

ok. i want to show the navigation bar like in picture above. when scrolling up then the navigation bar appear. for now when scrolling up, the navigation bar was hiding right. So how to show the navigation bar like the picture above when scrolling up the list.

**Comment by syarizat** [comment]
Hello Mukyasa,

So is there any solution or u are still not clear about my question.

**Comment by mukyasa** [comment]
Hello RodrigezJson,
Please check this function ,The logic of showing the navigation bar and horizontal tab is in this method, To be precise this is `UIView` which looks like navigation bar.

`func scrollYAxis(offset:CGFloat ,translation:CGPoint)`

This is module where u see the navigation bar.You can modify logic according to your needs

```
else{
                            if(offset > 220   ){
                                  UIView.animateWithDuration(0.3, delay: 0, options: [], animations: { () -> Void in
                                    self.horiScroll.backgroundColor=self.currentColor
                                    self.navBar.backgroundColor=self.currentColor
                                    self.navTitle.alpha=1;
                                    self.indicatorcolor.backgroundColor=UIColor.whiteColor()
                                    self.horiScroll.contentInset = UIEdgeInsetsMake(0, 0, 0, 0.0);
                                    //                            horiScroll.contentOffset=CGPointMake(0, 0)
                                    self.horiScroll.scrollRectToVisible(self.labels[self.currentPage].frame, animated: true)

                                    }, completion: nil)


                        }

```

**Comment by syarizat** [comment]
ok thanks a lot @mukyasa . i will try it first.
