### ISSUE TITLE
Not Allowing Me To Scroll To Next Tab

### ISSUE THREAD

**Issue by dannybess** [mukyasa/MMGooglePlayNewsStand#2]
Hi, 

I am not sure what happened, but after editing the ViewController file and the NewsCell file, I am no longer able to scroll past the second tab.

For example, if I have tabs: Sports, News, Columns, Spotlight:
I will be able to go from Sports to News, but when trying to go from News to Columns, I will be met with resistance. (bounce back animation)

**Comment by mukyasa** [comment]
can u attach the screenshot of problem your are facing, it will be more clear to me

**Comment by dannybess** [comment]
![simulator screen shot nov 26 2015 11 51 05 am](https://cloud.githubusercontent.com/assets/6439944/11429955/00219a9e-9434-11e5-8227-d877f35a5544.png)

I cannot go from News to the next tab by scrolling horizontally. (It blocks me.)

**Comment by mukyasa** [comment]
i cannot get the error, It may be related to scrollview issue.I have added the constraint for the viewcontroller's view programmatically.Please check for constraint which u may have added.

**Comment by mukyasa** [comment]
Check the new ObjCPlayStand Demo, its based on frame based not constraint based hope this help you

**Comment by dannybess** [comment]
Hi Mukesh,

By looking at the code I managed to get rid of the loading screen. I have
the smallest issue though - if I call
self.presentVC(appDelegate.walkthrough!), the controller seems to sort of
"reload". (I set the storyboard entry point at the
MMGooglePlayStandViewController)
