### ISSUE TITLE
What are required files to include ?

### ISSUE THREAD

**Issue by chlebta** [mukyasa/MMGooglePlayNewsStand#3]
Also I get this error  : 

> Use of undeclared type 'scrolldelegateForYAxis'

at this line : 

> @objc class MMPlayStandPageViewController: UIViewController,UIScrollViewDelegate,scrolldelegateForYAxis,UIGestureRecognizerDelegate {

<img width="316" alt="screen shot 2015-12-09 at 17 08 02" src="https://cloud.githubusercontent.com/assets/1204608/11690548/81be41e8-9e97-11e5-874d-08d46a77686e.png">

**Comment by mukyasa** [comment]
the viewcontroller viz u r gonna add should have below protocol and should confirm `MMPlayPageScroll`
check the demo and particularly `MMSampleTableViewController` how you have to add it .

```
@objc protocol scrolldelegateForYAxis{

    @objc optional func scrollYAxis(offset:CGFloat , translation:CGPoint)              // If the skipRequest(sender:) action is connected to a button, this function is called when that button is pressed.

    @objc optional func getframeindexpathOfController()->CGRect
}

```

**Comment by chlebta** [comment]
Thanks but what are required file to include, methods ... ? how to integrate it in existing project because I see lot of variable and method in `PlayStandViewController` and `SampleTableViewController`  and I can't figure which code to use and not.

**Comment by mukyasa** [comment]
you have to include `MMPlayStandPageViewController` and implement protocol as i suggested in above comment,Or you can make base view controller and subclass it for `MMSampleTableViewController` so u dnt have to write that code again and again.

also sorry as i had not made this project ready to go type(means like library) , but yes you just have to focus on above two files only and also the demo is self explanatory.

**Comment by chlebta** [comment]
@mukyasa why viewWillAppear and didAppear not called while scrolling between pages ? they are called only first time

**Comment by mukyasa** [comment]
Actually in this project, The controller are not loaded lazily, They are created and called only once.U may have to change the implementation to make it lazy loading .

**Comment by chlebta** [comment]
How to do it any guidance ?
Also what are bannerThin and alpha !! ?

**Comment by mukyasa** [comment]
you may have to go through the examples of `UIPageViewController` where the controller are loaded lazily, or similar to that.

**Comment by mukyasa** [comment]
chcek the ObjCPlayStand Demo and Git instructions for necessary required files
